# directories
data_dir: ./data/
train_path: ./data/train.csv
valid_path: ./data/valid.csv
out_dir: ./results/
out_dir_root: ./results/

# logging
verbosity: 2

# data parameters
max_len: 50

# trainer
epochs: 20
save_period: 1
monitor: min val_loss
early_stop: 10

# model parameters
batch_size: 16
learning_rate: 0.00002

n_gpu: 1